package org.beShare.gui;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

/**
 * MenuBar - The MenuBar for JavaShare 2. This class constructs the entire
 * Menu bar and all sub-menus, and registers which object ActionEvents should
 * be sent to.
 * <p/>
 * Class Started: 2-08-2002
 * Last Update: 4-27-2002
 *
 * @author Bryan Varner
 * @version 1.1
 */

public class SwingMenuBar extends JMenuBar {
	ActionListener actionTarget;
	JMenu menuFile;
	JMenuItem itemFileConnect;
	JMenuItem itemFileDisconnect;
	JMenuItem itemFileExit;
	JMenuItem itemFilePrivate;
	JMenuItem itemFileClearChat;
	JMenuItem itemFileAbout;
	JMenuItem itemFileSpawn;

	JMenu menuEdit;
	JMenuItem itemEditCut;
	JMenuItem itemEditCopy;
	JMenuItem itemEditPaste;
	JMenuItem itemEditPrefs;

	/**
	 * Creates a new menuBar that sends all ActionEvents generated by menu
	 * items to <code>actionTarget</code>
	 */
	public SwingMenuBar(ActionListener target) {
		super();
		actionTarget = target;

	}
}
