package org.beShare.gui;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;

/**
 * MenuBar - The MenuBar for JavaShare 2. This class constructs the entire
 * Menu bar and all sub-menus, and registers which object ActionEvents should
 * be sent to.
 * <p/>
 * Class Started: 2-08-2002
 * Last Update: 4-27-2002
 *
 * @author Bryan Varner
 * @version 1.1
 */

public class SwingMenuBar extends JMenuBar {
	ActionListener actionTarget;
	JMenu menuFile;
	JMenuItem itemFileConnect;
	JMenuItem itemFileDisconnect;
	JMenuItem itemFileExit;
	JMenuItem itemFilePrivate;
	JMenuItem itemFileClearChat;
	JMenuItem itemFileAbout;
	JMenuItem itemFileSpawn;

	JMenu menuEdit;
	JMenuItem itemEditCut;
	JMenuItem itemEditCopy;
	JMenuItem itemEditPaste;
	JMenuItem itemEditPrefs;

	/**
	 * Creates a new menuBar that sends all ActionEvents generated by menu
	 * items to <code>actionTarget</code>
	 */
	public SwingMenuBar(ActionListener target, boolean isApplet) {
		super();
		actionTarget = target;

		menuFile = new JMenu("File");
		menuFile.setMnemonic(KeyEvent.VK_F);

		menuEdit = new JMenu("Edit");
		menuEdit.setMnemonic(KeyEvent.VK_E);

		itemFileConnect = new JMenuItem("Connect", KeyEvent.VK_N);
		itemFileConnect.setActionCommand("menuConnect");
		itemFileConnect.addActionListener(actionTarget);
		itemFileConnect.setAccelerator(KeyStroke.getKeyStroke(
				                                                     KeyEvent.VK_N, ActionEvent.ALT_MASK));

		itemFileDisconnect = new JMenuItem("Disconnect", KeyEvent.VK_I);
		itemFileDisconnect.setActionCommand("menuDisconnect");
		itemFileDisconnect.addActionListener(actionTarget);
		itemFileDisconnect.setAccelerator(KeyStroke.getKeyStroke(
				                                                        KeyEvent.VK_B, ActionEvent.ALT_MASK + ActionEvent.SHIFT_MASK));

		itemFilePrivate = new JMenuItem("Open Private Chat Window", KeyEvent.VK_C);
		itemFilePrivate.setActionCommand("menuPrivate");
		itemFilePrivate.addActionListener(actionTarget);
		itemFilePrivate.setAccelerator(KeyStroke.getKeyStroke(
				                                                     KeyEvent.VK_C, ActionEvent.ALT_MASK));

		itemFileClearChat = new JMenuItem("Clear Chat Log", KeyEvent.VK_L);
		itemFileClearChat.setActionCommand("menuClear");
		itemFileClearChat.addActionListener(actionTarget);
		itemFileClearChat.setAccelerator(KeyStroke.getKeyStroke(
				                                                       KeyEvent.VK_L, ActionEvent.ALT_MASK));

		itemFileAbout = new JMenuItem("About JavaShare 2", KeyEvent.VK_A);
		itemFileAbout.setActionCommand("menuAbout");
		itemFileAbout.addActionListener(actionTarget);

		if (!isApplet) {
			itemFileExit = new JMenuItem("Quit", KeyEvent.VK_Q);
			itemFileExit.setActionCommand("menuQuit");
			itemFileExit.addActionListener(actionTarget);
			itemFileExit.setAccelerator(KeyStroke.getKeyStroke(
					                                                  KeyEvent.VK_Q, ActionEvent.ALT_MASK));
		} else {
			itemFileSpawn = new JMenuItem("Spawn Applet to Window"
					                             , KeyEvent.VK_W);
			itemFileSpawn.setActionCommand("spawn");
			itemFileSpawn.addActionListener(actionTarget);
			itemFileSpawn.setAccelerator(KeyStroke.getKeyStroke(
					                                                   KeyEvent.VK_W, ActionEvent.ALT_MASK));
		}

		menuFile.add(itemFileConnect);
		menuFile.add(itemFileDisconnect);
		menuFile.addSeparator();
		menuFile.add(itemFilePrivate);
		menuFile.add(itemFileClearChat);
		menuFile.addSeparator();
		menuFile.add(itemFileAbout);
		menuFile.addSeparator();
		if (!isApplet) {
			menuFile.add(itemFileExit);
		} else {
			menuFile.add(itemFileSpawn);
		}
		itemEditCut = new JMenuItem("Cut", KeyEvent.VK_C);
		itemEditCut.setActionCommand("cut");
		itemEditCut.addActionListener(actionTarget);
		itemEditCut.setAccelerator(KeyStroke.getKeyStroke(
				                                                 KeyEvent.VK_X, ActionEvent.CTRL_MASK));

		itemEditCopy = new JMenuItem("Copy", KeyEvent.VK_O);
		itemEditCopy.setActionCommand("copy");
		itemEditCopy.addActionListener(actionTarget);
		itemEditCopy.setAccelerator(KeyStroke.getKeyStroke(
				                                                  KeyEvent.VK_C, ActionEvent.CTRL_MASK));

		itemEditPaste = new JMenuItem("Paste", KeyEvent.VK_T);
		itemEditPaste.setActionCommand("paste");
		itemEditPaste.addActionListener(actionTarget);
		itemEditPaste.setAccelerator(KeyStroke.getKeyStroke(
				                                                   KeyEvent.VK_V, ActionEvent.CTRL_MASK));

		itemEditPrefs = new JMenuItem("Preferences", KeyEvent.VK_P);
		itemEditPrefs.setActionCommand("prefs");
		itemEditPrefs.addActionListener(actionTarget);
		itemEditPrefs.setAccelerator(KeyStroke.getKeyStroke(
				                                                   KeyEvent.VK_P, ActionEvent.ALT_MASK));

		menuEdit.add(itemEditCut);
		menuEdit.add(itemEditCopy);
		menuEdit.add(itemEditPaste);
		menuEdit.addSeparator();
		menuEdit.add(itemEditPrefs);

		this.add(menuFile);
		this.add(menuEdit);
	}
}
